- name: Disable selinux
  hosts: all
  become: true
  roles: 
    - selinux-disable

- name: Install nginx for webservers
  hosts: webservers
  become: true
  roles: 
    - webservers

- name: Install haproxy and keepalived for balancer
  hosts: balancer
  become: true
  roles: 
    - balancer