FROM alpine:latest

RUN apk --no-cache add nginx mc vim bash curl \
    && mkdir -p /var/www/html \
    && mkdir -p /run/nginx \
    && chown -R www-val:www-val /var/lib/nginx /var/www/html \
    && chown -R www-val:www-val /var/log/nginx \

COPY nginx.conf /etc/nginx/
COPY index.php /var/www/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


